[package]
name = "daql_analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {workspace = true}
public_function = {path = "../public_function"}
entity_lib = {path = "../entity_lib"}
serde = {workspace = true}
serde_json = {workspace = true}