[package]
name = "data-lake-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true}
serde = { workspace = true }
serde_json = { workspace = true }
snap = {workspace = true}
bincode = {workspace = true}


entity_lib = {path = "../entity_lib"}
